/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html", "./*.js"],
  safelist: [
    "md:col-span-4",
    "md:col-span-8",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#53b4c7",
        "on-primary-fixed": "#290055",
        "tertiary-fixed": "#a3eeff",
        "on-tertiary-fixed-variant": "#004e5a",
        "surface-tint": "#d7baff",
        "on-error": "#690005",
        surface: "#151218",
        "on-tertiary": "#00363e",
        background: "#151218",
        secondary: "#ffafd7",
        "inverse-surface": "#e8e0e9",
        "inverse-on-surface": "#332f36",
        "primary-container": "#bd93f9",
        "outline-variant": "#4a4451",
        tertiary: "#75d4e8",
        "inverse-primary": "#714aaa",
        "surface-dim": "#151218",
        "surface-container-low": "#1d1a21",
        "surface-container": "#211e25",
        "secondary-fixed": "#ffd8e9",
        "primary-fixed-dim": "#d7baff",
        "on-tertiary-fixed": "#001f25",
        "on-primary": "#411478",
        "on-surface": "#e8e0e9",
        error: "#ffb4ab",
        "on-secondary-fixed": "#3c0029",
        "on-secondary-fixed-variant": "#860f60",
        "surface-variant": "#37333a",
        "secondary-container": "#860f60",
        "on-primary-fixed-variant": "#593090",
        "surface-container-high": "#2c292f",
        "surface-bright": "#3b383f",
        "secondary-fixed-dim": "#ffafd7",
        outline: "#968e9c",
        "on-tertiary-container": "#00434d",
        "on-error-container": "#ffdad6",
        "on-background": "#e8e0e9",
        "on-primary-container": "#4e2484",
        "on-surface-variant": "#ccc3d3",
        "on-secondary-container": "#ff92cd",
        "error-container": "#93000a",
        "primary-fixed": "#eddcff",
        "on-secondary": "#620044",
        primary: "#d7baff",
        "surface-container-highest": "#37333a",
        "surface-container-lowest": "#100d13",
        "tertiary-fixed-dim": "#75d4e8",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1200px",
        base: "8px",
        "margin-desktop": "64px",
        "margin-mobile": "24px",
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        code: ["JetBrains Mono", "monospace"],
        "body-lg": ["JetBrains Mono", "monospace"],
        h2: ["EB Garamond", "serif"],
        "body-md": ["JetBrains Mono", "monospace"],
        "h1-mobile": ["EB Garamond", "serif"],
        h1: ["EB Garamond", "serif"],
      },
      fontSize: {
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "700" },
        ],
        code: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        h2: ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "h1-mobile": ["40px", { lineHeight: "1.1", fontWeight: "800" }],
        h1: [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
      },
    },
  },
};
